# This file was generated by GoReleaser. DO NOT EDIT.
cask "gskill" do
  version "0.7.2"

  on_macos do
    on_arm do
      sha256 "fff4b9c8fbec25b9c665300348abc58cb928b58c8c94d5b7edb22ae6a7171686"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "746e09504b13bc10760cb8b3ae1393f6777f9f6c381b03d296025ada1f26eb51"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6a996d8bab6cf1bfb58b3202328fe4f5f001d12b1f522467be00abd01502b441"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2115e3df1e90655d26fc0a5193e347c961778bea574e6584733d86488605f364"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gskill"
  desc "Reproducible package manager for agentic AI skills"
  homepage "https://github.com/glapsfun/gskill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gskill"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gskill"]
    end
  end

  # No zap stanza required
end
