# This file was generated by GoReleaser. DO NOT EDIT.
cask "gskill" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "b3feb6c9661cfec2a2023b714b56b4dc1822b7a1a86e50864163035504d6ded3"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9eabdbe7bcbadb39f336ce1ea121bc801266d3629c464945b5562ba9565874fb"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7064e15589c6a3b5eccf9d96062c5c23db49c413abf7552c1de371c14bc927fa"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b3c7ee2c97f4f11b8babbc334d98173c3f3972d60162b57caf69aba97fa352b"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gskill"
  desc "Reproducible package manager for agentic AI skills"
  homepage "https://github.com/glapsfun/gskill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gskill"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gskill"]
    end
  end

  # No zap stanza required

end
