# This file was generated by GoReleaser. DO NOT EDIT.
cask "gskill" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "f1e0c127ce7466f720c1c9fd23196a266ace4d8bbca38bccddd803800b6c6688"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1db2a903f4833537f933b7bf656289dd1836f6c02d28128c3d999e5c0f5472ae"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "17205cbd07a8ba362455bb89f4c8928ad7cc248670b1cfb19a664b04816db1b2"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e52018c6ce7e0cb3917dcf938aabe37cfcb2751d674f85bc337af64bfd42a810"
      url "https://github.com/glapsfun/gskill/releases/download/v#{version}/gskill_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gskill"
  desc "Reproducible package manager for agentic AI skills"
  homepage "https://github.com/glapsfun/gskill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gskill"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gskill"]
    end
  end

  # No zap stanza required

end
