# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "dadc607fe1846fd139b6d0ae29fb8378865d41dcd651ca714767745d9fa3b9fe"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4370676cd9932846a15cd36b409ffb844aaf1b62be5cb2420d64e67265a4540b"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "be6a5bd42387977776103c27288dfc640de1305f9ce854d6042fcd546578631a"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a189960cd17eceec1940ac097ba996238fb39b624d02db1b71aa9389fd0f7ae"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rune"
  desc "A shared task runner for humans and AI agents"
  homepage "https://github.com/glapsfun/rune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rune"]
    end
  end

  # No zap stanza required

end
