# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d0744365c9ca7230a137848e1339ccb1feccaf8abff2cefc47b881aeeca0915b"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fff86dbe382a5bac0ea30a94437b12ac6a17c1b671be1de97c23277d887f9590"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db170a342bd8dac35749a7a4eee2d8b6a0eb614c29bac0fcc8aa04f1541b80f5"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3e2f59a62770660e363db947670faeab62c00d275f7cece3321a981759ce9f0"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rune"
  desc "A shared task runner for humans and AI agents"
  homepage "https://github.com/glapsfun/rune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rune"]
    end
  end

  # No zap stanza required

end
