# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "4190066365f04b5fedd7f52ba99be4e4bbff26be6d76806bedbb8d5514bda063"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f685dea196c3a6389a6ea890f1cf7bc98fc8d291ea8098b5ef79818b34cbe537"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4e357b8465236e6741fe0c0edb8f27a22c5758cfb9dd6c512571f44a7b61a74"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4cf5e4bdc7dd673cd7733cf278d9e4ffa361bfc1c8f7815547fdb434f9292033"
      url "https://github.com/glapsfun/rune/releases/download/v#{version}/rune_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rune"
  desc "A shared task runner for humans and AI agents"
  homepage "https://github.com/glapsfun/rune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rune"]
    end
  end

  # No zap stanza required

end
